function returnToMainTab() {
	$("#tab-scoped-1").removeClass("slds-hide");
	$("#tab-scoped-1").addClass("slds-show");
	$("#tab-scoped-2").removeClass("slds-show");
	$("#tab-scoped-2").addClass("slds-hide");
	$("#tab-scoped-3").removeClass("slds-show");
	$("#tab-scoped-3").addClass("slds-hide");
	$("#tab-scoped-4").removeClass("slds-show");
	$("#tab-scoped-4").addClass("slds-hide");
	$("#tab-scoped-5").removeClass("slds-show");
	$("#tab-scoped-5").addClass("slds-hide");
	$("#tab-scoped-6").removeClass("slds-show");
	$("#tab-scoped-6").addClass("slds-hide");
	$("#tab-scoped-7").removeClass("slds-show");
	$("#tab-scoped-7").addClass("slds-hide");
	$("#tab1").addClass("slds-active");
	$("#tab2").removeClass("slds-active");
	$("#tab3").removeClass("slds-active");
	$("#tab4").removeClass("slds-active");
	$("#tab5").removeClass("slds-active");
	$("#tab6").removeClass("slds-active");
	$("#tab7").removeClass("slds-active");
}

function switchTab(tabNumber) {
	if(tabNumber == '1') {
		$("#tab-scoped-1").removeClass("slds-hide");
		$("#tab-scoped-1").addClass("slds-show");
		$("#tab-scoped-2").removeClass("slds-show");
		$("#tab-scoped-2").addClass("slds-hide");
		$("#tab-scoped-3").removeClass("slds-show");
		$("#tab-scoped-3").addClass("slds-hide");
		$("#tab-scoped-4").removeClass("slds-show");
		$("#tab-scoped-4").addClass("slds-hide");
		$("#tab-scoped-5").removeClass("slds-show");
		$("#tab-scoped-5").addClass("slds-hide");
		$("#tab-scoped-6").removeClass("slds-show");
		$("#tab-scoped-6").addClass("slds-hide");
		$("#tab-scoped-7").removeClass("slds-show");
		$("#tab-scoped-7").addClass("slds-hide");
		$("#tab1").addClass("slds-active");
		$("#tab2").removeClass("slds-active");
		$("#tab3").removeClass("slds-active");
		$("#tab4").removeClass("slds-active");
		$("#tab5").removeClass("slds-active");
		$("#tab6").removeClass("slds-active");
		$("#tab7").removeClass("slds-active");
	}
	if(tabNumber == '2') {
		$("#tab-scoped-1").removeClass("slds-show");
		$("#tab-scoped-1").addClass("slds-hide");
		$("#tab-scoped-2").removeClass("slds-hide");
		$("#tab-scoped-2").addClass("slds-show");
		$("#tab-scoped-3").removeClass("slds-show");
		$("#tab-scoped-3").addClass("slds-hide");
		$("#tab-scoped-4").removeClass("slds-show");
		$("#tab-scoped-4").addClass("slds-hide");
		$("#tab-scoped-5").removeClass("slds-show");
		$("#tab-scoped-5").addClass("slds-hide");
		$("#tab-scoped-6").removeClass("slds-show");
		$("#tab-scoped-6").addClass("slds-hide");
		$("#tab-scoped-7").removeClass("slds-show");
		$("#tab-scoped-7").addClass("slds-hide");
		$("#tab1").removeClass("slds-active");
		$("#tab2").addClass("slds-active");
		$("#tab3").removeClass("slds-active");
		$("#tab4").removeClass("slds-active");
		$("#tab5").removeClass("slds-active");
		$("#tab6").removeClass("slds-active");
		$("#tab7").removeClass("slds-active");
	}
	if(tabNumber == '3') {
		$("#tab-scoped-1").removeClass("slds-show");
		$("#tab-scoped-1").addClass("slds-hide");
		$("#tab-scoped-2").removeClass("slds-show");
		$("#tab-scoped-2").addClass("slds-hide");
		$("#tab-scoped-3").removeClass("slds-hide");
		$("#tab-scoped-3").addClass("slds-show");
		$("#tab-scoped-4").removeClass("slds-show");
		$("#tab-scoped-4").addClass("slds-hide");
		$("#tab-scoped-5").removeClass("slds-show");
		$("#tab-scoped-5").addClass("slds-hide");
		$("#tab-scoped-6").removeClass("slds-show");
		$("#tab-scoped-6").addClass("slds-hide");
		$("#tab-scoped-7").removeClass("slds-show");
		$("#tab-scoped-7").addClass("slds-hide");
		$("#tab1").removeClass("slds-active");
		$("#tab2").removeClass("slds-active");
		$("#tab3").addClass("slds-active");
		$("#tab4").removeClass("slds-active");
		$("#tab5").removeClass("slds-active");
		$("#tab6").removeClass("slds-active");
		$("#tab7").removeClass("slds-active");
	}
	if(tabNumber == '4') {
		$("#tab-scoped-1").removeClass("slds-show");
		$("#tab-scoped-1").addClass("slds-hide");
		$("#tab-scoped-2").removeClass("slds-show");
		$("#tab-scoped-2").addClass("slds-hide");
		$("#tab-scoped-3").removeClass("slds-show");
		$("#tab-scoped-3").addClass("slds-hide");
		$("#tab-scoped-4").removeClass("slds-hide");
		$("#tab-scoped-4").addClass("slds-show");
		$("#tab-scoped-5").removeClass("slds-show");
		$("#tab-scoped-5").addClass("slds-hide");
		$("#tab-scoped-6").removeClass("slds-show");
		$("#tab-scoped-6").addClass("slds-hide");
		$("#tab-scoped-7").removeClass("slds-show");
		$("#tab-scoped-7").addClass("slds-hide");
		$("#tab1").removeClass("slds-active");
		$("#tab2").removeClass("slds-active");
		$("#tab3").removeClass("slds-active");
		$("#tab4").addClass("slds-active");
		$("#tab5").removeClass("slds-active");
		$("#tab6").removeClass("slds-active");
		$("#tab7").removeClass("slds-active");
	}
	if(tabNumber == '5') {
		$("#tab-scoped-1").removeClass("slds-show");
		$("#tab-scoped-1").addClass("slds-hide");
		$("#tab-scoped-2").removeClass("slds-show");
		$("#tab-scoped-2").addClass("slds-hide");
		$("#tab-scoped-3").removeClass("slds-show");
		$("#tab-scoped-3").addClass("slds-hide");
		$("#tab-scoped-4").removeClass("slds-show");
		$("#tab-scoped-4").addClass("slds-hide");
		$("#tab-scoped-5").removeClass("slds-hide");
		$("#tab-scoped-5").addClass("slds-show");
		$("#tab-scoped-6").removeClass("slds-show");
		$("#tab-scoped-6").addClass("slds-hide");
		$("#tab-scoped-7").removeClass("slds-show");
		$("#tab-scoped-7").addClass("slds-hide");
		$("#tab1").removeClass("slds-active");
		$("#tab2").removeClass("slds-active");
		$("#tab3").removeClass("slds-active");
		$("#tab4").removeClass("slds-active");
		$("#tab5").addClass("slds-active");
		$("#tab6").removeClass("slds-active");
		$("#tab7").removeClass("slds-active");
	}
	if(tabNumber == '6') {
		$("#tab-scoped-1").removeClass("slds-show");
		$("#tab-scoped-1").addClass("slds-hide");
		$("#tab-scoped-2").removeClass("slds-show");
		$("#tab-scoped-2").addClass("slds-hide");
		$("#tab-scoped-3").removeClass("slds-show");
		$("#tab-scoped-3").addClass("slds-hide");
		$("#tab-scoped-4").removeClass("slds-show");
		$("#tab-scoped-4").addClass("slds-hide");
		$("#tab-scoped-5").removeClass("slds-show");
		$("#tab-scoped-5").addClass("slds-hide");
		$("#tab-scoped-6").removeClass("slds-hide");
		$("#tab-scoped-6").addClass("slds-show");
		$("#tab-scoped-7").removeClass("slds-show");
		$("#tab-scoped-7").addClass("slds-hide");
		$("#tab1").removeClass("slds-active");
		$("#tab2").removeClass("slds-active");
		$("#tab3").removeClass("slds-active");
		$("#tab4").removeClass("slds-active");
		$("#tab5").removeClass("slds-active");
		$("#tab6").addClass("slds-active");
		$("#tab7").removeClass("slds-active");
	}
	if(tabNumber == '7') {
	    $("#tab-scoped-1").removeClass("slds-show");
		$("#tab-scoped-1").addClass("slds-hide");
		$("#tab-scoped-2").removeClass("slds-show");
		$("#tab-scoped-2").addClass("slds-hide");
		$("#tab-scoped-3").removeClass("slds-show");
		$("#tab-scoped-3").addClass("slds-hide");
		$("#tab-scoped-4").removeClass("slds-show");
		$("#tab-scoped-4").addClass("slds-hide");
		$("#tab-scoped-5").removeClass("slds-show");
		$("#tab-scoped-5").addClass("slds-hide");
		$("#tab-scoped-6").removeClass("slds-show");
		$("#tab-scoped-6").addClass("slds-hide");
		$("#tab-scoped-7").removeClass("slds-hide");
		$("#tab-scoped-7").addClass("slds-show");
		$("#tab1").removeClass("slds-active");
		$("#tab2").removeClass("slds-active");
		$("#tab3").removeClass("slds-active");
		$("#tab4").removeClass("slds-active");
		$("#tab5").removeClass("slds-active");
		$("#tab6").removeClass("slds-active");
		$("#tab7").addClass("slds-active");
	}
}